Removed `./` from `customConfig` input `url`
Having a flake input of type `path` starting with `./` was causing
errors like this:

```
error: cannot fetch input 'path:./custom-config?lastModified=1&narHash=sha256-Zd5w1I1Dwt783Q4WuBuCpedcwG1DrIgQGqabyF87prM=' because it uses a relative path
```